### PR TITLE
Job page

### PR DESCRIPTION
**Pull request by coderBelal**

### CODE REVIEW

**Comment by yeasin2002** [comment]
Have you completed everything on the job page?

**Comment by coderBelal** [comment]
i think yes sir you can check. is everything ok or not? if everything not
ok say me i will do

**Comment by coderBelal** [comment]
i think yes sir you can check. is everything ok or not? if everything not ok say me i will do

**Comment by yeasin2002** [comment]
Jobs cards are not looking good, event it's overflowing in mobile device. 


image

**Comment by coderBelal** [comment]
Ok, I'll check it out.

**Pull request merged**
